spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:h2:file:C:\\Users\\Dell\\Downloads\\app\\Java-workspace\\product-db