package com.jdev.prodready.api.product.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "products_2")
@NoArgsConstructor
@AllArgsConstructor
@Data
public class Product2 {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "col_1")
    private String col1;
    @Column(name = "col_2")
    private String col2;
    @Column(name = "col_3")
    private String col3;
    @Column(name = "col_4")
    private String col4;
    @Column(name = "col_5")
    private String col5;
    @Column(name = "col_6")
    private String col6;
    @Column(name = "col_7")
    private String col7;
    @Column(name = "col_8")
    private String col8;
    @Column(name = "col_9")
    private String col9;
    @Column(name = "col_10")
    private String col10;

    @Column(name = "col_11")
    private String col11;
    @Column(name = "col_12")
    private String col12;
    @Column(name = "col_13")
    private String col13;
    @Column(name = "col_14")
    private String col14;
    @Column(name = "col_15")
    private String col15;
    @Column(name = "col_16")
    private String col16;
    @Column(name = "col_17")
    private String col17;
    @Column(name = "col_18")
    private String col18;
    @Column(name = "col_19")
    private String col19;
    @Column(name = "col_20")
    private String col20;

    @Column(name = "col_21")
    private String col21;
    @Column(name = "col_22")
    private String col22;
    @Column(name = "col_23")
    private String col23;
    @Column(name = "col_24")
    private String col24;
    @Column(name = "col_25")
    private String col25;
    @Column(name = "col_26")
    private String col26;
    @Column(name = "col_27")
    private String col27;
    @Column(name = "col_28")
    private String col28;
    @Column(name = "col_29")
    private String col29;
    @Column(name = "col_30")
    private String col30;

    @Column(name = "col_31")
    private String col31;
    @Column(name = "col_32")
    private String col32;
    @Column(name = "col_33")
    private String col33;
    @Column(name = "col_34")
    private String col34;
    @Column(name = "col_35")
    private String col35;
    @Column(name = "col_36")
    private String col36;
    @Column(name = "col_37")
    private String col37;
    @Column(name = "col_38")
    private String col38;
    @Column(name = "col_39")
    private String col39;
    @Column(name = "col_40")
    private String col40;

    @Column(name = "col_41")
    private String col41;
    @Column(name = "col_42")
    private String col42;
    @Column(name = "col_43")
    private String col43;
    @Column(name = "col_44")
    private String col44;
    @Column(name = "col_45")
    private String col45;
    @Column(name = "col_46")
    private String col46;
    @Column(name = "col_47")
    private String col47;
    @Column(name = "col_48")
    private String col48;
    @Column(name = "col_49")
    private String col49;
    @Column(name = "col_50")
    private String col50;

    @Column(name = "col_51")
    private String col51;
    @Column(name = "col_52")
    private String col52;
    @Column(name = "col_53")
    private String col53;
    @Column(name = "col_54")
    private String col54;
    @Column(name = "col_55")
    private String col55;
    @Column(name = "col_56")
    private String col56;
    @Column(name = "col_57")
    private String col57;
    @Column(name = "col_58")
    private String col58;
    @Column(name = "col_59")
    private String col59;
    @Column(name = "col_60")
    private String col60;

    @Column(name = "col_61")
    private String col61;
    @Column(name = "col_62")
    private String col62;
    @Column(name = "col_63")
    private String col63;
    @Column(name = "col_64")
    private String col64;
    @Column(name = "col_65")
    private String col65;
    @Column(name = "col_66")
    private String col66;
    @Column(name = "col_67")
    private String col67;
    @Column(name = "col_68")
    private String col68;
    @Column(name = "col_69")
    private String col69;
    @Column(name = "col_70")
    private String col70;

    @Column(name = "col_71")
    private String col71;
    @Column(name = "col_72")
    private String col72;
    @Column(name = "col_73")
    private String col73;
    @Column(name = "col_74")
    private String col74;
    @Column(name = "col_75")
    private String col75;
    @Column(name = "col_76")
    private String col76;
    @Column(name = "col_77")
    private String col77;
    @Column(name = "col_78")
    private String col78;
    @Column(name = "col_79")
    private String col79;
    @Column(name = "col_80")
    private String col80;

    @Column(name = "col_81")
    private String col81;
    @Column(name = "col_82")
    private String col82;
    @Column(name = "col_83")
    private String col83;
    @Column(name = "col_84")
    private String col84;
    @Column(name = "col_85")
    private String col85;
    @Column(name = "col_86")
    private String col86;
    @Column(name = "col_87")
    private String col87;
    @Column(name = "col_88")
    private String col88;
    @Column(name = "col_89")
    private String col89;
    @Column(name = "col_90")
    private String col90;

    @Column(name = "col_91")
    private String col91;
    @Column(name = "col_92")
    private String col92;
    @Column(name = "col_93")
    private String col93;
    @Column(name = "col_94")
    private String col94;
    @Column(name = "col_95")
    private String col95;
    @Column(name = "col_96")
    private String col96;
    @Column(name = "col_97")
    private String col97;
    @Column(name = "col_98")
    private String col98;
    @Column(name = "col_99")
    private String col99;
    @Column(name = "col_100")
    private String col100;

    @Column(name = "col_101")
    private String col101;
    @Column(name = "col_102")
    private String col102;
    @Column(name = "col_103")
    private String col103;
    @Column(name = "col_104")
    private String col104;
    @Column(name = "col_105")
    private String col105;
    @Column(name = "col_106")
    private String col106;
    @Column(name = "col_107")
    private String col107;
    @Column(name = "col_108")
    private String col108;
    @Column(name = "col_109")
    private String col109;
    @Column(name = "col_110")
    private String col110;

    @Column(name = "col_111")
    private String col111;
    @Column(name = "col_112")
    private String col112;
    @Column(name = "col_113")
    private String col113;
    @Column(name = "col_114")
    private String col114;
    @Column(name = "col_115")
    private String col115;
    @Column(name = "col_116")
    private String col116;
    @Column(name = "col_117")
    private String col117;
    @Column(name = "col_118")
    private String col118;
    @Column(name = "col_119")
    private String col119;
    @Column(name = "col_120")
    private String col120;

    @Column(name = "col_121")
    private String col121;
    @Column(name = "col_122")
    private String col122;
    @Column(name = "col_123")
    private String col123;
    @Column(name = "col_124")
    private String col124;
    @Column(name = "col_125")
    private String col125;
    @Column(name = "col_126")
    private String col126;
    @Column(name = "col_127")
    private String col127;
    @Column(name = "col_128")
    private String col128;
    @Column(name = "col_129")
    private String col129;
    @Column(name = "col_130")
    private String col130;

    @Column(name = "col_131")
    private String col131;
    @Column(name = "col_132")
    private String col132;
    @Column(name = "col_133")
    private String col133;
    @Column(name = "col_134")
    private String col134;
    @Column(name = "col_135")
    private String col135;
    @Column(name = "col_136")
    private String col136;
    @Column(name = "col_137")
    private String col137;
    @Column(name = "col_138")
    private String col138;
    @Column(name = "col_139")
    private String col139;
    @Column(name = "col_140")
    private String col140;

    @Column(name = "col_141")
    private String col141;
    @Column(name = "col_142")
    private String col142;
    @Column(name = "col_143")
    private String col143;
    @Column(name = "col_144")
    private String col144;
    @Column(name = "col_145")
    private String col145;
    @Column(name = "col_146")
    private String col146;
    @Column(name = "col_147")
    private String col147;
    @Column(name = "col_148")
    private String col148;
    @Column(name = "col_149")
    private String col149;
    @Column(name = "col_150")
    private String col150;

    @Column(name = "col_151")
    private String col151;
    @Column(name = "col_152")
    private String col152;
    @Column(name = "col_153")
    private String col153;
    @Column(name = "col_154")
    private String col154;
    @Column(name = "col_155")
    private String col155;
    @Column(name = "col_156")
    private String col156;
    @Column(name = "col_157")
    private String col157;
    @Column(name = "col_158")
    private String col158;
    @Column(name = "col_159")
    private String col159;
    @Column(name = "col_160")
    private String col160;

    @Column(name = "col_161")
    private String col161;
    @Column(name = "col_162")
    private String col162;
    @Column(name = "col_163")
    private String col163;
    @Column(name = "col_164")
    private String col164;
    @Column(name = "col_165")
    private String col165;
    @Column(name = "col_166")
    private String col166;
    @Column(name = "col_167")
    private String col167;
    @Column(name = "col_168")
    private String col168;
    @Column(name = "col_169")
    private String col169;
    @Column(name = "col_170")
    private String col170;

    @Column(name = "col_171")
    private String col171;
    @Column(name = "col_172")
    private String col172;
    @Column(name = "col_173")
    private String col173;
    @Column(name = "col_174")
    private String col174;
    @Column(name = "col_175")
    private String col175;
    @Column(name = "col_176")
    private String col176;
    @Column(name = "col_177")
    private String col177;
    @Column(name = "col_178")
    private String col178;
    @Column(name = "col_179")
    private String col179;
    @Column(name = "col_180")
    private String col180;

    @Column(name = "col_181")
    private String col181;
    @Column(name = "col_182")
    private String col182;
    @Column(name = "col_183")
    private String col183;
    @Column(name = "col_184")
    private String col184;
    @Column(name = "col_185")
    private String col185;
    @Column(name = "col_186")
    private String col186;
    @Column(name = "col_187")
    private String col187;
    @Column(name = "col_188")
    private String col188;
    @Column(name = "col_189")
    private String col189;
    @Column(name = "col_190")
    private String col190;

    @Column(name = "col_191")
    private String col191;
    @Column(name = "col_192")
    private String col192;
    @Column(name = "col_193")
    private String col193;
    @Column(name = "col_194")
    private String col194;
    @Column(name = "col_195")
    private String col195;
    @Column(name = "col_196")
    private String col196;
    @Column(name = "col_197")
    private String col197;
    @Column(name = "col_198")
    private String col198;
    @Column(name = "col_199")
    private String col199;
    @Column(name = "col_200")
    private String col200;
}
